# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        
        # Style général de l'application
        MainWindow.setStyleSheet("""
            QMainWindow {
                background-color: #f0f0f0;
            }
            QLabel {
                font-size: 12px;
                font-weight: bold;
                color: #333;
            }
            QPushButton {
                background-color: #2196F3;
                color: white;
                border: none;
                padding: 8px 15px;
                border-radius: 4px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #1976D2;
            }
            QLineEdit, QDateEdit, QComboBox {
                padding: 6px;
                border: 1px solid #ddd;
                border-radius: 4px;
                background-color: white;
            }
            QTableWidget {
                background-color: white;
                border: 1px solid #ddd;
                border-radius: 4px;
            }
            QTableWidget::item {
                padding: 5px;
            }
            QTableWidget::item:selected {
                background-color: #2196F3;
                color: white;
            }
        """)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Layout principal
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(20, 20, 20, 20)
        self.main_layout.setSpacing(15)
        
        # Section de recherche
        self.search_frame = QtWidgets.QFrame()
        self.search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_frame.setStyleSheet("QFrame { background-color: white; border-radius: 8px; padding: 10px; }")
        self.search_layout = QtWidgets.QHBoxLayout(self.search_frame)
        
        self.label = QtWidgets.QLabel("Matricule")
        self.matricule_search = QtWidgets.QLineEdit()
        self.matricule_search.setPlaceholderText("Entrez le matricule...")
        self.btn_rechercher = QtWidgets.QPushButton("Rechercher")
        
        self.search_layout.addWidget(self.label)
        self.search_layout.addWidget(self.matricule_search)
        self.search_layout.addWidget(self.btn_rechercher)
        self.main_layout.addWidget(self.search_frame)
        
        # Section du formulaire
        self.form_frame = QtWidgets.QFrame()
        self.form_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.form_frame.setStyleSheet("QFrame { background-color: white; border-radius: 8px; padding: 15px; }")
        self.form_layout = QtWidgets.QFormLayout(self.form_frame)
        self.form_layout.setSpacing(10)
        
        # Champs du formulaire
        self.nom_input = QtWidgets.QLineEdit()
        self.prenom_input = QtWidgets.QLineEdit()
        self.date_naissance_input = QtWidgets.QDateEdit()
        self.date_naissance_input.setCalendarPopup(True)
        
        # Widget pour les boutons radio
        self.sexe_widget = QtWidgets.QWidget()
        self.sexe_layout = QtWidgets.QHBoxLayout(self.sexe_widget)
        self.sexe_layout.setContentsMargins(0, 0, 0, 0)
        self.radio_f = QtWidgets.QRadioButton("F")
        self.radio_h = QtWidgets.QRadioButton("H")
        self.sexe_layout.addWidget(self.radio_f)
        self.sexe_layout.addWidget(self.radio_h)
        
        # Combobox pour filière et niveau
        self.filiere_combo = QtWidgets.QComboBox()
        self.filiere_combo.addItems(["Informatique", "Gestion", "Mécanique"])
        self.niveau_combo = QtWidgets.QComboBox()
        self.niveau_combo.addItems(["1ère année", "2ème année", "3ème année"])
        
        # Ajout des champs au formulaire
        self.form_layout.addRow("Nom:", self.nom_input)
        self.form_layout.addRow("Prénom:", self.prenom_input)
        self.form_layout.addRow("Date de naissance:", self.date_naissance_input)
        self.form_layout.addRow("Sexe:", self.sexe_widget)
        self.form_layout.addRow("Filière:", self.filiere_combo)
        self.form_layout.addRow("Niveau:", self.niveau_combo)
        
        self.main_layout.addWidget(self.form_frame)
        
        # Boutons d'action
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setSpacing(10)
        
        self.btn_actualiser = QtWidgets.QPushButton("Actualiser")
        self.btn_ajouter = QtWidgets.QPushButton("Insertion")
        self.btn_modifier = QtWidgets.QPushButton("Modification")
        self.btn_supprimer = QtWidgets.QPushButton("Suppression")
        
        self.btn_supprimer.setStyleSheet("background-color: #f44336;")
        
        self.buttons_layout.addWidget(self.btn_actualiser)
        self.buttons_layout.addWidget(self.btn_ajouter)
        self.buttons_layout.addWidget(self.btn_modifier)
        self.buttons_layout.addWidget(self.btn_supprimer)
        
        self.main_layout.addLayout(self.buttons_layout)
        
        # Table des étudiants
        self.table_frame = QtWidgets.QFrame()
        self.table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_frame.setStyleSheet("QFrame { background-color: white; border-radius: 8px; padding: 10px; }")
        self.table_layout = QtWidgets.QVBoxLayout(self.table_frame)
        
        self.table_etudiants = QtWidgets.QTableWidget()
        self.table_etudiants.setColumnCount(7)
        self.table_etudiants.setHorizontalHeaderLabels([
            "Matricule", "Nom", "Prénom", "Date de naissance",
            "Sexe", "Filière", "Niveau"
        ])
        
        # Configuration de la table
        self.table_etudiants.horizontalHeader().setStretchLastSection(True)
        self.table_etudiants.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.Stretch)
        self.table_etudiants.setAlternatingRowColors(True)
        self.table_etudiants.setSelectionBehavior(
            QtWidgets.QTableWidget.SelectRows)
        self.table_etudiants.setSelectionMode(
            QtWidgets.QTableWidget.SingleSelection)
        
        self.table_layout.addWidget(self.table_etudiants)
        self.main_layout.addWidget(self.table_frame)
        
        # Définir le widget central
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Connexions des signaux
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # État initial des boutons radio
        self.radio_f.setChecked(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestion des étudiants"))
        self.label.setText(_translate("MainWindow", "Matricule"))
        self.btn_rechercher.setText(_translate("MainWindow", "Rechercher"))
        self.label_2.setText(_translate("MainWindow", "Nom"))
        self.label_3.setText(_translate("MainWindow", "Prénom"))
        self.label_4.setText(_translate("MainWindow", "Date de naissance"))
        self.label_5.setText(_translate("MainWindow", "Sexe"))
        self.radio_f.setText(_translate("MainWindow", "F"))
        self.radio_h.setText(_translate("MainWindow", "H"))
        self.label_6.setText(_translate("MainWindow", "Filière"))
        self.filiere_combo.setItemText(0, _translate("MainWindow", "Informatique"))
        self.filiere_combo.setItemText(1, _translate("MainWindow", "Gestion"))
        self.filiere_combo.setItemText(2, _translate("MainWindow", "Mécanique"))
        self.label_7.setText(_translate("MainWindow", "Niveau"))
        self.niveau_combo.setItemText(0, _translate("MainWindow", "1ère année"))
        self.niveau_combo.setItemText(1, _translate("MainWindow", "2ème année"))
        self.niveau_combo.setItemText(2, _translate("MainWindow", "3ème année"))
        self.btn_actualiser.setText(_translate("MainWindow", "Actualiser"))
        self.btn_ajouter.setText(_translate("MainWindow", "Insertion"))
        self.btn_modifier.setText(_translate("MainWindow", "Modification"))
        self.btn_supprimer.setText(_translate("MainWindow", "Suppression"))
        item = self.table_etudiants.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Matricule"))
        item = self.table_etudiants.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nom"))
        item = self.table_etudiants.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Prénom"))
        item = self.table_etudiants.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date de naissance"))
        item = self.table_etudiants.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sexe"))
        item = self.table_etudiants.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Filière"))
        item = self.table_etudiants.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Niveau"))
